version: 2

jobs:
  node:
    working_directory: ~/repo
    docker:
      - image: circleci/node:11.10.1
    steps:
      - checkout

      - restore_cache:
          key: yarn-v1-{{ checksum "yarn.lock" }}-{{ arch }}

      - restore_cache:
          key: node-v1-{{ checksum "package.json" }}-{{ arch }}

      - run: yarn install

      - save_cache:
          key: yarn-v1-{{ checksum "yarn.lock" }}-{{ arch }}
          paths:
              - ~/.cache/yarn

      - save_cache:
          key: node-v1-{{ checksum "package.json" }}-{{ arch }}
          paths:
              - node_modules

      - run: yarn lint

      - run:
          name: run test
          command: |
              if [ -n "$COVERALLS_REPO_TOKEN" ]; then
                  yarn test --maxWorkers=2 --coverage --coverageReporters=text-lcov | ./node_modules/coveralls/bin/coveralls.js
              else
                  yarn test --maxWorkers=2
              fi

      - persist_to_workspace:
          root: ~/repo
          paths:
            - node_modules

  ios:
    macos:
      xcode: "11.2.1"
    working_directory: ~/repo

    environment:
      FL_OUTPUT_DIR: output
      FASTLANE_LANE: beta

    shell: /bin/bash --login -o pipefail

    steps:
      - checkout

      - restore_cache:
          key: yarn-v1-{{ checksum "yarn.lock" }}-{{ arch }}

      - restore_cache:
          key: node-v1-{{ checksum "package.json" }}-{{ arch }}

      - run: yarn install

      - save_cache:
          key: yarn-v1-{{ checksum "yarn.lock" }}-{{ arch }}
          paths:
              - ~/.cache/yarn

      - save_cache:
          key: node-v1-{{ checksum "package.json" }}-{{ arch }}
          paths:
              - node_modules

      - restore_cache:
          key: bundle-v1-{{ checksum "ios/Gemfile.lock" }}-{{ arch }}

      - run:
          command: bundle install
          working_directory: ios

      - run:
          command: bundle update fastlane
          working_directory: ios

      - save_cache:
          key: bundle-v1-{{ checksum "ios/Gemfile.lock" }}-{{ arch }}
          paths:
            - vendor/bundle

      - run:
          name: Fastlane
          command: bundle exec fastlane $FASTLANE_LANE
          working_directory: ios

      - store_artifacts:
          path: output

workflows:
  version: 2
  node-ios:
    jobs:
      - node
      - ios:
          requires:
            - node
          filters:
            branches:
              only: master
